version: '3.3'
services:
  user_db:
    build: .
    networks:
      - bookstore
    environment:
      MYSQL_ROOT_PASSWORD: asdfgh
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"

networks:
  bookstore:
    external: true
